apiVersion: batch/v1
kind: Job
metadata:
  name: train-sampler
  labels:
    experiment: train-sampler-instance
spec:
  template:
    spec:
      containers:
      - name: train-sampler
        image: lukeshimanuki/guiding_gtamp_light:latest
        imagePullPolicy: Always
        command: ['bash']
        args:
          - '-c'
          - 'cd /guiding_gtamp_light
          && sed -i "s/url = git@github.com:/url = http:\/\/github.com\//" .git/config && git fetch
          && git checkout -- .
          && git rev-parse HEAD
          && nvidia-smi' # ; mc config host add lis https://ceph.csail.mit.edu ${S3ACCESS} ${S3SECRET}; mc cp -r test_results lis/guiding-gtamp; echo finished'
        envFrom:
          - secretRef:
              name: openstack-s3
        resources:
          limits:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 1
          requests:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 1
      restartPolicy: Never

