apiVersion: batch/v1
kind: Job
metadata:
  name: NAME-greedyh
  labels:
    experiment: NAME-greedyh
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      containers:
      - name: NAME-greedyh
        image: lukeshimanuki/guiding_gtamp_light:latest
        imagePullPolicy: Always
        command: ['bash']
        args:
        - '-c'
        - 'mc config host add lis https://ceph.csail.mit.edu ${S3ACCESS} ${S3SECRET} && (for i in {kinematics.4f95c55204252b6edd6332624a20624c,kinematics.9ff4f1d77a61494bbd09f843fedb0314,robot.7edbf73fb4fc856e8294d93279d26ff2}; do mc cp -r lis/bkim/ik/${i} ~/.openrave; done) && cd /guiding_gtamp_light && sed -i "s/url = git@github.com:/url = http:\/\/github.com\//" .git/config && git fetch && git checkout COMMIT && for a in DOMAINS; do for n in NUMOBJ_RANGE; do for i in PIDX_RANGE; do for j in SEEDS; do echo planning for a $a n $n pidx $i seed $j; PYTHONPATH=/guiding_gtamp_light/openrave_wrapper/manipulation:/guiding_gtamp_light/openrave_wrapper:/guiding_gtamp_light:/guiding_gtamp_light/mover_library:/pddlstream timeout $((600*$n))s python2 test_scripts/run_greedy.py -pidx=$i -n_objs_pack=$n -domain=${a}_arm_mover -planner_seed=$j -pick_sampler_seed=$j -loading_sampler_seed=$j -home_sampler_seed=$j -timelimit=$((500*$n)) -n_mp_limit=5 -n_iter_limit=2000 -h_option=hcount_old_number_in_goal -f; done; done; done; done; mc cp -r test_results lis/guiding-gtamp; echo finished'
        envFrom:
          - secretRef:
              name: OPENSTACKSECRETSREF
        resources:
          limits:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 0
          requests:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 0
      restartPolicy: Never

