apiVersion: batch/v1
kind: Job
metadata:
  name: NAME
  labels:
    experiment: NAME
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker
      containers:
      - name: NAME
        image: lukeshimanuki/guiding_gtamp_light:latest
        imagePullPolicy: Always
        command: ['bash']
        args:
          - '-c'
          - 'cd /guiding_gtamp_light
          && sed -i "s/url = git@github.com:/url = http:\/\/github.com\//" .git/config
          && git config --global user.email "beomjoon.kim0@gmail.com"
          && git fetch --all
          && git reset --hard origin/beomjoon
          && git checkout 511b915934af3a63a7dd3b29f45133fbc496fbb8
          && git log --pretty=format:%h -n 1
          && mc config host add csail https://ceph.csail.mit.edu 119df3538de4475aaf3f0737600003b4 7e0b2e1e15004eafb75f49d1f265baf7
          && mc cp csail/bkim/ik/kinematics.9ff4f1d77a61494bbd09f843fedb0314 ~/.openrave/ --recursive
          && mc cp csail/bkim/ik/kinematics.4f95c55204252b6edd6332624a20624c ~/.openrave/ --recursive
          && mc cp csail/bkim/ik/robot.7edbf73fb4fc856e8294d93279d26ff2 ~/.openrave/ --recursive
          && mc cp csail/bkim/ik/robot.7edbf73fb4fc856e8294d93279d26ff2 ~/.openrave/ --recursive
          && mkdir -p ./planning_experience/raw/two_arm_mover/n_objs_pack_1/hcount_old_number_in_goal/q_config_num_train_5000_mse_weight_1.0_use_region_agnostic_False_mix_rate_1.0/n_mp_limit_5_n_iter_limit_2000/
          && mc cp csail/bkim/guiding-gtamp/planning_experience/raw/two_arm_mover/n_objs_pack_1/hcount_old_number_in_goal/q_config_num_train_5000_mse_weight_1.0_use_region_agnostic_False_mix_rate_1.0/n_mp_limit_5_n_iter_limit_2000/sampling_strategy_uniformpidx_PIDX_planner_seed_0_gnn_seed_0.pkl ./planning_experience/raw/two_arm_mover/n_objs_pack_1/hcount_old_number_in_goal/q_config_num_train_5000_mse_weight_1.0_use_region_agnostic_False_mix_rate_1.0/n_mp_limit_5_n_iter_limit_2000/
          && export PYTHONPATH=/guiding_gtamp_light/openrave_wrapper/manipulation:/guiding_gtamp_light/openrave_wrapper:/guiding_gtamp_light:/guiding_gtamp_light/mover_library:/pddlstream
          && python data_processing/TYPE/process_planning_experience.py -pidx PIDX
          && ls ./
          && mc cp -r planning_experience/ csail/bkim/guiding-gtamp; echo finished'
        envFrom:
          - secretRef:
              name: openstack-s3
        resources:
          limits:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 0
          requests:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 0
      restartPolicy: Never

