apiVersion: batch/v1
kind: Job
metadata:
  name: NAME
  labels:
    experiment: NAME
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      imagePullSecrets:
        - name: docker
      containers:
      - name: NAME
        image: lukeshimanuki/guiding_gtamp_light:latest
        imagePullPolicy: Always
        command: ['bash']
        args:
          - '-c'
          - 'cd /guiding_gtamp_light
          && sed -i "s/url = git@github.com:/url = http:\/\/github.com\//" .git/config
          && git config --global user.email "beomjoon.kim0@gmail.com"
          && git fetch --all
          && git reset --hard origin/beomjoon
          && git log --pretty=format:%h -n 1
          && mc config host add csail https://ceph.csail.mit.edu 119df3538de4475aaf3f0737600003b4 7e0b2e1e15004eafb75f49d1f265baf7 && mc cp csail/bkim/ik/kinematics.9ff4f1d77a61494bbd09f843fedb0314 ~/.openrave/ --recursive && mc cp csail/bkim/ik/kinematics.4f95c55204252b6edd6332624a20624c ~/.openrave/ --recursive && mc cp csail/bkim/ik/robot.7edbf73fb4fc856e8294d93279d26ff2 ~/.openrave/ --recursive && export PYTHONPATH=/guiding_gtamp_light/openrave_wrapper/manipulation:/guiding_gtamp_light/openrave_wrapper:/guiding_gtamp_light:/guiding_gtamp_light/mover_library:/pddlstream
          && python ./test_scripts/run_greedy.py -pidx PIDX -planner_seed PLANSEED -domain one_arm_mover -mse_weight 1.0 -h_option qlearned_hcount_old_number_in_goal -problem_type normal -pick_architecture fc -n_mp_limit 5 -num_node_limit 3000 -absq_seed 0 -pick_sampler_seed 2 -place_architecture fc -n_iter_limit 500 -mixrate 1.0 -loss largemargin -num_train 5000 -n_objs_pack 1 -atype place -explr_p 0.3 -timelimit 1000 -home_sampler_seed 0 -loading_sampler_seed 1
          && mc cp -r test_results csail/bkim/guiding-gtamp; echo finished'
        envFrom:
          - secretRef:
              name: openstack-s3
        resources:
          limits:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 0
          requests:
            cpu: 3
            memory: 12Gi
            nvidia.com/gpu: 0
      restartPolicy: Never

